# Generated by Django 2.2.3 on 2019-09-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/%y/%m/%d/'),
        ),
    ]
