# Generated by Django 2.2.3 on 2019-09-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messages_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='picture',
            new_name='m',
        ),
    ]
