# Generated by Django 2.2.3 on 2019-09-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190903_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='m',
            new_name='picture',
        ),
    ]
