# Generated by Django 2.2.3 on 2019-09-08 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20190904_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations',
            name='members',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
