# Generated by Django 2.2.3 on 2019-09-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20190908_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
