# Generated by Django 2.2.3 on 2019-09-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_conversations_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='last_message',
        ),
    ]
