# Generated by Django 2.2.3 on 2019-09-15 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_messages_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='date_modified',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
