# Generated by Django 2.2.3 on 2019-08-23 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190816_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='token',
        ),
        migrations.AddField(
            model_name='users',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='verificationtoken',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
