# Generated by Django 2.2.3 on 2019-09-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190823_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='verificationtoken',
            field=models.UUIDField(default='<function uuid4 at 0x7efe6fe51a60>', null=True),
        ),
    ]
