# Generated by Django 2.2.3 on 2019-09-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190901_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='verificationtoken',
            field=models.CharField(default='<function uuid4 at 0x7f0a10779a60>', max_length=200, null=True),
        ),
    ]
