# Generated by Django 2.2.3 on 2019-09-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_users_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
