# Generated by Django 2.2.3 on 2019-09-04 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190904_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contacts',
            field=models.ManyToManyField(null=True, related_name='_users_contacts_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
